### ISSUE TITLE
Restore Power on Bridge not working?

### ISSUE THREAD

**Issue by robaxx** [Techgeek20/7D2D-Carrier_Challenge#10]
I may have done something wrong, not sure.

I've completed the 2 UH 60 tasks and then it gave me the one to restore power on the bridge.

I had already been to the bridge previously and had seen the 2 generators and also cleared out the zombies. So I've been back there twice now, including at night, to try and complete the quest, but there's nothing to do. There's no trigger, and I can't do anything to the generators.

As mentioned, I have been there before and scavenged the upper floors for iron from all the computers etc. When I did that, the antennae tower on top started to collapse. I recall seeing a signpost up there earlier saying something about power and visiting the trader. That is now gone.

Is that why I can't complete this?
Thanks for any advice on this.

I looked for a Discord for this but can't find one, so I'm asking here.

**Comment by Techgeek20** [comment]
Which commit version is this issue happening on?  If the most recent version (b6bafb8), we'll look into it.

**Comment by robaxx** [comment]
I use the 7D2D mod launcher and update every time the update button comes on, which happens quite often. There's never any release number or release notes in there.

I'm looking in the game folder for a release number.. can't see one in the readme.md or in the AircraftCarrierChallenge.xml. Is there somewhere I can see it?

**Comment by Devilskut** [comment]
\7D2D\Alpha21\Aircraft_Carrier\Aircraft_Carrier\ModConfig\Archive will list the versions downloaded . Description should be merge pull #9 {latest} on the Mod Launcher. Thanks DK

**Comment by robaxx** [comment]
hmm.. nothing seems to match that. There's no Archive and no ModConfig folder anywhere in 7D2D. 

I've only ever used the mod launcher to install these things and I don't change any defaults.

I'll put a screenshot in here.

![Aircraft_Carrier](https://github.com/Techgeek20/7D2D-Carrier_Challenge/assets/6693281/414eb903-59b7-4ada-aa0b-8aaa90737a14)

**Comment by Techgeek20** [comment]
Most recent commit tag is: b6baf.
