### ISSUE TITLE
Locking item slots in inventory does not work

### ISSUE THREAD

**Issue by theloser** [Techgeek20/7D2D-Carrier_Challenge#12]
Using the latest version 1.0.1.1 of this mod pack, and no matter if I play as a single user on my PC or playing with others on my dedicated server, locking slots in the player's inventory doesn't work for me/us. Sorting the inventory ignores locked slots.

EDIT: To be more precise: the built-in locking mechanism of A21 (using the "<#>" in the inventory screen) doesn't work; I just figured out this mod-pack comes with a mod where you have to use the "X" key to lock slots.

**Comment by Techgeek20** [comment]
The modlet to lock inventory slots using the "X" key to lock slots overrides the vanilla (a.k.a. built-in) method of inventory locking.  Hope this helps.  When slots are locked using the "X" key, those inventory slots are no longer sortable, nor those slots empty when transferring into storages.

**Comment by theloser** [comment]
Thanks, I've figured that out right after posting the issue. Then again, why using a mod to achieve this behavior when it's already a "vanilla" feature? Also, playing on a dedicated server, sometimes I/we just can't press X to (un)lock slots, just doesn't work.
