### ISSUE TITLE
On Server: "Restocking" time inconsistent

### ISSUE THREAD

**Issue by theloser** [Techgeek20/7D2D-Carrier_Challenge#13]
When playing on a server, the "Restocking" time of containers is inconsistent. It shows "Day 7, 10am" for one player and "Day 9, 10am" for another player for exactly the same container.

Also: is there any specific `serverconfig.xml` setting that we need to use to set the time for restocking, or is it using the default "LootRespawnDays" one?

**Comment by Techgeek20** [comment]
LootRespawnDays option in the serverconfig.xml file should be default (7 days).

**Comment by theloser** [comment]
Thanks! After changing the LootRespawnDays settings to 7 days, it now seems to work.
