### ISSUE TITLE
POI stability needs to be addressed.

### ISSUE THREAD

**Issue by FishOutOfH20** [Techgeek20/7D2D-Carrier_Challenge#3]
The stability needs to be improved.  I wrenched a single gas pump after clearing debris, and brought a huge chunk of the POI down.  I had to end the run due to screamers  after that.

The following images should help you to locate the weakness:

Failure in progress:

![failure](https://github.com/Techgeek20/7D2D-Carrier_Challenge/assets/57605132/dc8a6fc5-0f3c-497d-b82b-97a4acaa56a5)

Failure location after in god mode to pinpoint it:

![failure2](https://github.com/Techgeek20/7D2D-Carrier_Challenge/assets/57605132/ef7e1a6b-ec6b-40e2-966b-e7f1f94d9092)

The gas pumps in question:
![failure location](https://github.com/Techgeek20/7D2D-Carrier_Challenge/assets/57605132/4f826885-2e7f-4c9e-baa3-a55e20d42b53)

Structural integrity of the pumps:
![failure stability](https://github.com/Techgeek20/7D2D-Carrier_Challenge/assets/57605132/ded98be2-ee55-4f96-8a68-a5297b08ecfe)

Other side of the pumps:
![stability other view](https://github.com/Techgeek20/7D2D-Carrier_Challenge/assets/57605132/5a77575e-2605-490f-852b-370296ab7317)

**Comment by Techgeek20** [comment]
Thanks for the additional stability issue location.  We've (Devilskut and I) have been finding some as we play and fix other "bugs".  Appreciate it :)

**Comment by Techgeek20** [comment]
Stability fix #1 completed.  If additional locations are found, feel free to update this issue ticket.
